import type { PersonalNumberMaster } from "./types";

/** あなたのすうじマスタ（キャラ・UD に依存しない固定メタ） */
export const PERSONAL_NUMBER_MASTERS: PersonalNumberMaster[] = [
  {
    lifePathNumber: 1,
    displayName: "すうじ1のあなたへ",
    subtitle: "始まりのすうじ",
    coreTheme: "自分から動く、小さな一歩",
    toneNotes: ["始めることを急がせすぎない"],
    avoidNotes: ["命令口調にしない"],
  },
  {
    lifePathNumber: 2,
    displayName: "すうじ2のあなたへ",
    subtitle: "繋がりのすうじ",
    coreTheme: "受け取る、やり取り、やわらかな関係",
    toneNotes: ["相手の気持ちを先に置く"],
    avoidNotes: ["依存を促さない"],
  },
  {
    lifePathNumber: 3,
    displayName: "すうじ3のあなたへ",
    subtitle: "表現のすうじ",
    coreTheme: "楽しさ、言葉、心が動くこと",
    toneNotes: ["軽やかさを残す"],
    avoidNotes: ["浅さだけに寄せない"],
  },
  {
    lifePathNumber: 4,
    displayName: "すうじ4のあなたへ",
    subtitle: "つみ重ねのすうじ",
    coreTheme: "積み重ね、現実的な整え",
    toneNotes: ["完璧を求めすぎない"],
    avoidNotes: ["硬さだけを強調しない"],
  },
  {
    lifePathNumber: 5,
    displayName: "すうじ5のあなたへ",
    subtitle: "自由のすうじ",
    coreTheme: "動き、冒険、新しい選択",
    toneNotes: ["自由を急がせない"],
    avoidNotes: ["不安を煽らない"],
  },
  {
    lifePathNumber: 6,
    displayName: "すうじ6のあなたへ",
    subtitle: "優しさのすうじ",
    coreTheme: "ケア、支え、あたたかさ",
    toneNotes: ["与えすぎを促さない"],
    avoidNotes: ["聖人化しない"],
  },
  {
    lifePathNumber: 7,
    displayName: "すうじ7のあなたへ",
    subtitle: "深めるすうじ",
    coreTheme: "静けさ、本質、深い気づき",
    toneNotes: ["孤立を強めすぎない"],
    avoidNotes: ["覚醒・魂などの表現を避ける"],
  },
  {
    lifePathNumber: 8,
    displayName: "すうじ8のあなたへ",
    subtitle: "手ごたえのすうじ",
    coreTheme: "現実化、手ごたえ、成果",
    toneNotes: ["成功を強く言いすぎない"],
    avoidNotes: ["お金・権力に寄せすぎない"],
  },
  {
    lifePathNumber: 9,
    displayName: "すうじ9のあなたへ",
    subtitle: "受けとめるすうじ",
    coreTheme: "区切り、余韻、次への流れ",
    toneNotes: ["手放しを強制しない"],
    avoidNotes: ["「手放すべき」と言わない"],
  },
  {
    lifePathNumber: 11,
    displayName: "すうじ11のあなたへ",
    subtitle: "ひらめきのすうじ",
    coreTheme: "インスピレーション、感性、ことば",
    toneNotes: ["特別感を煽らない"],
    avoidNotes: ["波動・宇宙などを使わない"],
  },
  {
    lifePathNumber: 22,
    displayName: "すうじ22のあなたへ",
    subtitle: "形づくるすうじ",
    coreTheme: "大きな理想を現実へ",
    toneNotes: ["重さを増しすぎない"],
    avoidNotes: ["使命を背負わせない"],
  },
  {
    lifePathNumber: 33,
    displayName: "すうじ33のあなたへ",
    subtitle: "深い愛のすうじ",
    coreTheme: "包む、照らす、やさしい導き",
    toneNotes: ["与えすぎを美徳にしない"],
    avoidNotes: ["無条件の与えを促さない"],
  },
];
