import { myPageActionIllustrations } from "@/lib/mypage/myPageActionAssets";

import { FIRST_VISIT_MILESTONE_HOME_BUTTON } from "@/lib/onboarding/firstVisitWizard/milestoneCopy";
import {
  KANTEI_FIRST_READ_BOOKSHELF_BODY,
  KANTEI_FIRST_READ_BOOKSHELF_OWL_QUOTE,
  KANTEI_FIRST_READ_BOOKSHELF_PRIMARY_BUTTON,
  KANTEI_FIRST_READ_COMPLETE_BODY,
  KANTEI_FIRST_READ_COMPLETE_OWL_QUOTE,
  KANTEI_FIRST_READ_COMPLETE_PRIMARY_BUTTON,
  KANTEI_FIRST_READ_COMPLETE_SECONDARY_BUTTON,
} from "@/lib/pdf/kanteiFirstReadGuideCopy";

/** 鑑定完了後・本棚の案内カード1 */
export const BOOKSHELF_KANTEI_GUIDE_CARD1_TITLE = "鑑定書が本棚に届きました" as const;

export const BOOKSHELF_KANTEI_GUIDE_CARD1_OWL_QUOTE = KANTEI_FIRST_READ_BOOKSHELF_OWL_QUOTE;

export const BOOKSHELF_KANTEI_GUIDE_CARD1_BODY = KANTEI_FIRST_READ_BOOKSHELF_BODY;

export const BOOKSHELF_KANTEI_GUIDE_CARD1_PRIMARY_BUTTON = KANTEI_FIRST_READ_BOOKSHELF_PRIMARY_BUTTON;

export const BOOKSHELF_KANTEI_GUIDE_CARD1_SECONDARY_BUTTON = FIRST_VISIT_MILESTONE_HOME_BUTTON;

export const BOOKSHELF_KANTEI_GUIDE_CARD1_ILLUSTRATION_SRC =
  myPageActionIllustrations.bookshelf.src;

/** 鑑定完了後・本棚の案内カード2 */
export const BOOKSHELF_KANTEI_GUIDE_CARD2_TITLE = "日記にも、ことばが届きます" as const;

export const BOOKSHELF_KANTEI_GUIDE_CARD2_BODY =
  "鑑定を受けたことで、\n今日のあしあとを残すときに\nどうぶつ鑑定士からのメッセージが\n届くようになりました。\n\nその日のすうじや、\nあなたが残した気持ちを手がかりに、\n森のどうぶつ鑑定士たちが\nそっと言葉を添えてくれます。\n\nこのあと、どうしますか？" as const;

export const BOOKSHELF_KANTEI_GUIDE_CARD2_PRIMARY_BUTTON = "あしあとを残してみる" as const;

export const BOOKSHELF_KANTEI_GUIDE_CARD2_SECONDARY_BUTTON = FIRST_VISIT_MILESTONE_HOME_BUTTON;

export const BOOKSHELF_KANTEI_GUIDE_CARD2_ILLUSTRATION_SRC =
  "/images/mypage/bookshelf_kantei_journal_owl.png" as const;

/** ライフパス初回読了オーバーレイ */
export const KANTEI_FIRST_READ_COMPLETE_OVERLAY_OWL_QUOTE = KANTEI_FIRST_READ_COMPLETE_OWL_QUOTE;

export const KANTEI_FIRST_READ_COMPLETE_OVERLAY_BODY = KANTEI_FIRST_READ_COMPLETE_BODY;

export const KANTEI_FIRST_READ_COMPLETE_OVERLAY_PRIMARY_BUTTON =
  KANTEI_FIRST_READ_COMPLETE_PRIMARY_BUTTON;

export const KANTEI_FIRST_READ_COMPLETE_OVERLAY_SECONDARY_BUTTON =
  KANTEI_FIRST_READ_COMPLETE_SECONDARY_BUTTON;
