/**
 * デザイン元 PDF ↔ 本番 PNG の対応表（差し替え時の取り違え防止用）。
 * プレビュー: /preview/pdf-design-map
 */
export type PdfDesignAssetEntry = {
  id: string;
  /** 鑑定書での説明（日本語） */
  label: string;
  /** `src/components/pdf/assets/` 内の本番 PNG（生成 PDF が参照） */
  runtimePng: string;
  /** 同フォルダのデザイン元 PDF（複数ある場合は aliases に旧名・別名） */
  designPdf: string | null;
  designPdfAliases?: string[];
  /** pdfAssetPaths.ts の定数名（参考） */
  codeConstant?: string;
  /** pdf-lib で PDF のまま結合（PNG 化しない） */
  mergePdfOnly?: boolean;
  note?: string;
};

/** クリック一覧の表示順 */
export const PDF_DESIGN_ASSET_ENTRIES: PdfDesignAssetEntry[] = [
  {
    id: "intro-1-bg",
    label: "はじめに 1ページ目（文字なし背景）",
    runtimePng: "introduction-page-1-bg.png",
    designPdf: null,
    codeConstant: "PDF_INTRODUCTION_PAGE_1_BG_PATH",
    note: "IntroductionPage1。文言は pdfIntroductionCopy.ts。",
  },
  {
    id: "intro-1",
    label: "はじめに 1ページ目（レガシー・文字込み）",
    runtimePng: "introduction-page-1.png",
    designPdf: "introduction-page-1.pdf",
    codeConstant: "PDF_INTRODUCTION_PAGE_1_PATH",
  },
  {
    id: "intro-2-bg",
    label: "はじめに 2ページ目（文字なし背景・2P移行用）",
    runtimePng: "introduction-page-2-bg.png",
    designPdf: null,
    codeConstant: "PDF_INTRODUCTION_PAGE_2_BG_PATH",
    note: "未配置時は introduction-page-2.png（全面）のまま。",
  },
  {
    id: "intro-2",
    label: "はじめに 2ページ目（レガシー・文字込み）",
    runtimePng: "introduction-page-2.png",
    designPdf: "introduction-page-2.pdf",
    codeConstant: "PDF_INTRODUCTION_PAGE_2_PATH",
  },
  {
    id: "inside-cover-bg",
    label: "中表紙（背景）",
    runtimePng: "inside-cover-page-bg.png",
    designPdf: "inside-cover-page.pdf",
    codeConstant: "PDF_INSIDE_COVER_PAGE_BG_PATH",
    note: "InsideCoverPage。Libre Baskerville・#574129・表紙サブタイトルと同文。",
  },
  {
    id: "inside-cover",
    label: "中表紙（レガシー・文字込み全面）",
    runtimePng: "inside-cover-page.png",
    designPdf: "inside-cover-page.pdf",
    codeConstant: "PDF_INSIDE_COVER_PAGE_PATH",
  },
  {
    id: "cover-bg",
    label: "表紙（背景）",
    runtimePng: "cover-template-bg.png",
    designPdf: "cover-template.pdf",
    codeConstant: "PDF_COVER_TEMPLATE_BG_PATH",
    note: "CoverPage。cover01 / cover02（Libre Baskerville）。",
  },
  {
    id: "cover",
    label: "表紙（レガシー・文字込み全面）",
    runtimePng: "cover-template.png",
    designPdf: "cover-template.pdf",
    codeConstant: "PDF_COVER_IMAGE_PATH",
  },
  {
    id: "chapter-divider-bg",
    label: "章扉・共通背景（第1〜4章）",
    runtimePng: "chapter-divider-bg.png",
    designPdf: null,
    codeConstant: "PDF_CHAPTER_DIVIDER_BG_PATH",
    note: "ChapterDividerBleedPage。chapter_no / chapter_title（Noto Sans JP・#545454）。",
  },
  {
    id: "ch1",
    label: "第1章扉（レガシー・文字込み全面）",
    runtimePng: "chapter-1-divider.png",
    designPdf: null,
    codeConstant: "PDF_CHAPTER_1_DIVIDER_PATH",
  },
  {
    id: "core-number-first-bg",
    label: "コア中間扉・共通背景（6種）",
    runtimePng: "core-number-first-bg.png",
    designPdf: null,
    codeConstant: "PDF_CORE_NUMBER_FIRST_BG_PATH",
    note: "CoreNumberIntroBleedPage。core ラベル（LP/Destiny/Soul/Personality/Birthday/Maturity）。",
  },
  {
    id: "number-guide-bg",
    label: "「〇〇ナンバーとは」共通背景（7ページ）",
    runtimePng: "number-guide-bg.png",
    designPdf: null,
    codeConstant: "PDF_NUMBER_GUIDE_BG_PATH",
    note: "LifePathGuidePage ほか7ページ共通。文字は pdfCoreNumberGuideCopy.ts。",
  },
  {
    id: "lp-guide",
    label: "「ライフパスナンバーとは」ガイド",
    runtimePng: "life-path-guide.png",
    designPdf: "life-path-guide.pdf",
    codeConstant: "PDF_LIFE_PATH_GUIDE_PAGE_PATH",
    note: "レガシー文字込みPNG。パイロット後も参照用に残置。",
  },
  {
    id: "lp-first",
    label: "ライフパス本文 1枚目（装飾背景）",
    runtimePng: "haikei-lp.png",
    designPdf: "haikei-lp2.pdf",
    designPdfAliases: ["haikei-lp.pdf"],
    codeConstant: "PDF_LIFE_PATH_FIRST_PAGE_PATH",
    note: "差し替え後は npm run fix:lp-bg-header の必要がある場合あり。",
  },
  {
    id: "destiny-guide",
    label: "「ディスティニーナンバーとは」ガイド",
    runtimePng: "destiny-guide.png",
    designPdf: "destiny-guide.pdf",
    codeConstant: "PDF_DESTINY_GUIDE_PAGE_PATH",
  },
  {
    id: "destiny-first",
    label: "ディスティニー本文 1枚目",
    runtimePng: "destiny-first-page.png",
    designPdf: "haikei_d2.pdf",
    designPdfAliases: ["haikei-distny.pdf", "destiny-first-page.pdf"],
    codeConstant: "PDF_DESTINY_FIRST_PAGE_PATH",
    note: "npm run fix:destiny-bg-header",
  },
  {
    id: "soul-guide",
    label: "「ソウルナンバーとは」ガイド",
    runtimePng: "soul-guide.png",
    designPdf: "soul-guide.pdf",
    codeConstant: "PDF_SOUL_GUIDE_PAGE_PATH",
  },
  {
    id: "soul-first",
    label: "ソウル本文 1枚目",
    runtimePng: "soul-first-page.png",
    designPdf: "haikei_s2.pdf",
    designPdfAliases: ["haikei-soul.pdf"],
    codeConstant: "PDF_SOUL_FIRST_PAGE_PATH",
    note: "npm run fix:soul-bg-header",
  },
  {
    id: "personality-guide",
    label: "「パーソナリティナンバーとは」ガイド",
    runtimePng: "personality-guide.png",
    designPdf: "personality-guide.pdf",
    codeConstant: "PDF_PERSONALITY_GUIDE_PAGE_PATH",
  },
  {
    id: "personality-first",
    label: "パーソナリティ本文 1枚目",
    runtimePng: "personality-first-page.png",
    designPdf: "haikei_p2.pdf",
    designPdfAliases: ["personality-first-page.pdf"],
    codeConstant: "PDF_PERSONALITY_FIRST_PAGE_PATH",
    note: "npm run fix:personality-bg-header",
  },
  {
    id: "birthday-guide",
    label: "「バースデーナンバーとは」ガイド",
    runtimePng: "birthday-guide.png",
    designPdf: "birthday-guide.pdf",
    codeConstant: "PDF_BIRTHDAY_GUIDE_PAGE_PATH",
  },
  {
    id: "birthday-first",
    label: "バースデー本文 1枚目",
    runtimePng: "birthday-first-page.png",
    designPdf: "haikei_b2.pdf",
    designPdfAliases: ["birthday-first-page.pdf"],
    codeConstant: "PDF_BIRTHDAY_FIRST_PAGE_PATH",
    note: "npm run fix:birthday-bg-header",
  },
  {
    id: "maturity-guide",
    label: "「マチュリティナンバーとは」ガイド",
    runtimePng: "maturity-guide.png",
    designPdf: "maturity-guide.pdf",
    codeConstant: "PDF_MATURITY_GUIDE_PAGE_PATH",
  },
  {
    id: "maturity-first",
    label: "マチュリティ本文 1枚目",
    runtimePng: "maturity-first-page.png",
    designPdf: "haikei_m2.pdf",
    designPdfAliases: ["maturity-first-page.pdf"],
    codeConstant: "PDF_MATURITY_FIRST_PAGE_PATH",
    note: "npm run fix:maturity-bg-header",
  },
  {
    id: "toc-bg",
    label: "目次・コア本文 2枚目以降の地",
    runtimePng: "haikei-kekka2.png",
    designPdf: null,
    codeConstant: "PDF_CORE_RESULT_CONTINUATION_BACKGROUND_PATH",
    note: "npm run fix:toc-continuation-bg-header。同名 PDF が無い場合あり。",
  },
  {
    id: "ch2",
    label: "第2章扉（レガシー・文字込み全面）",
    runtimePng: "chapter-2-divider.png",
    designPdf: null,
  },
  {
    id: "py-message-bg",
    label: "パーソナルイヤー前・フクロウメッセージ（文字なし背景）",
    runtimePng: "personal-year-message-bg.png",
    designPdf: null,
    codeConstant: "PDF_PERSONAL_YEAR_MESSAGE_BG_PATH",
    note: "PersonalYearMessagePage。文言は pdfPersonalYearMessageCopy.ts。",
  },
  {
    id: "py-message",
    label: "パーソナルイヤー前・フクロウメッセージ（レガシー）",
    runtimePng: "personal-year-message.png",
    designPdf: "personal-year-message.pdf",
    codeConstant: "PDF_PERSONAL_YEAR_MESSAGE_PAGE_PATH",
  },
  {
    id: "py-guide",
    label: "パーソナルイヤー導入",
    runtimePng: "personal-year-guide.png",
    designPdf: "personal-year-guide.pdf",
    codeConstant: "PDF_PERSONAL_YEAR_GUIDE_PAGE_PATH",
  },
  {
    id: "py-chapter-transition",
    label: "パーソナルイヤー章末装飾（鳥の足跡・全面）",
    runtimePng: "personal-year-chapter-transition.png",
    designPdf: "chapter-insert-before-4.pdf",
    codeConstant: "PDF_PERSONAL_YEAR_CHAPTER_TRANSITION_PATH",
    note: "PersonalYearChapterTransitionPage。旧 blank02。フクロウ章後メッセージの直前。",
  },
  {
    id: "py-after-message-bg",
    label: "パーソナルイヤー章後・フクロウ先生メッセージ（文字なし背景）",
    runtimePng: "personal-year-after-message-bg.png",
    designPdf: null,
    codeConstant: "PDF_PERSONAL_YEAR_AFTER_MESSAGE_BG_PATH",
    note: "PersonalYearAfterMessagePage。46_ue / 46_shita。文言は pdfPersonalYearAfterMessageCopy.ts。",
  },
  {
    id: "ch3",
    label: "第3章扉（レガシー・文字込み全面）",
    runtimePng: "chapter-3-divider.png",
    designPdf: null,
  },
  {
    id: "insert-ch3",
    label: "第3章扉直前に挿入（PDF結合のみ）",
    runtimePng: "",
    designPdf: "chapter-insert-before-3.pdf",
    codeConstant: "PDF_CHAPTER_INSERT_BEFORE_3_PATH",
    mergePdfOnly: true,
    note: "PNG ではなく PDF のまま結合。軽量化はこの PDF ファイル自体を差し替え。",
  },
  {
    id: "bridge-after-message-bg",
    label: "ブリッジ章後・フクロウメッセージ（文字なし背景）",
    runtimePng: "bridge-after-message-bg.png",
    designPdf: null,
    codeConstant: "PDF_BRIDGE_AFTER_MESSAGE_BG_PATH",
    note: "BridgeAfterMessagePage。hon_bridge-after-message。文言は pdfBridgeAfterMessageCopy.ts。",
  },
  {
    id: "bridge-guide-1-bg",
    label: "ブリッジ「とは」1P（文字なし背景）",
    runtimePng: "bridge-guide-page-1-bg.png",
    designPdf: null,
    codeConstant: "PDF_BRIDGE_GUIDE_PAGE_1_BG_PATH",
    note: "BridgeIntroPages 1P。title_bri / hon_bri01。文言は pdfBridgeGuideCopy.ts。",
  },
  {
    id: "bridge-guide-2-bg",
    label: "ブリッジ「とは」2P（文字なし背景）",
    runtimePng: "bridge-guide-page-2-bg.png",
    designPdf: null,
    codeConstant: "PDF_BRIDGE_GUIDE_PAGE_2_BG_PATH",
    note: "BridgeIntroPages 2P。hon_bri02。",
  },
  {
    id: "bridge-intro-1",
    label: "ブリッジ導入 1（レガシー）",
    runtimePng: "bridge-intro-1.png",
    designPdf: "bridge-intro-1.pdf",
    codeConstant: "PDF_BRIDGE_INTRO_PAGE_1_PATH",
  },
  {
    id: "bridge-intro-2",
    label: "ブリッジ導入 2（レガシー）",
    runtimePng: "bridge-intro-2.png",
    designPdf: "bridge-intro-2.pdf",
    codeConstant: "PDF_BRIDGE_INTRO_PAGE_2_PATH",
  },
  {
    id: "bridge-cover",
    label: "ブリッジ章扉（レガシー・旧PY章後フクロウ全面と同一画像）",
    runtimePng: "bridge-section-cover.png",
    designPdf: "bridge-section-cover.pdf",
    codeConstant: "PDF_BRIDGE_SECTION_COVER_PATH",
    note: "鑑定PDFでは未使用。第3章扉は chapter-3-divider.png / Chapter3DividerPage。",
  },
  {
    id: "bridge-star-1",
    label: "ブリッジ星 1",
    runtimePng: "bridge-star-1.png",
    designPdf: null,
    codeConstant: "PDF_BRIDGE_STAR_1_PATH",
  },
  {
    id: "bridge-star-2",
    label: "ブリッジ星 2",
    runtimePng: "bridge-star-2.png",
    designPdf: null,
    codeConstant: "PDF_BRIDGE_STAR_2_PATH",
  },
  {
    id: "bridge-star-3",
    label: "ブリッジ星 3",
    runtimePng: "bridge-star-3.png",
    designPdf: null,
    codeConstant: "PDF_BRIDGE_STAR_3_PATH",
  },
  {
    id: "bridge-star-4",
    label: "ブリッジ星 4",
    runtimePng: "bridge-star-4.png",
    designPdf: null,
    codeConstant: "PDF_BRIDGE_STAR_4_PATH",
  },
  {
    id: "bridge-star-5",
    label: "ブリッジ星 5",
    runtimePng: "bridge-star-5.png",
    designPdf: null,
    codeConstant: "PDF_BRIDGE_STAR_5_PATH",
  },
  {
    id: "insert-ch4",
    label: "第4章扉直前に挿入（PDF結合のみ・旧PY章後メッセージ）",
    runtimePng: "",
    designPdf: "chapter-insert-before-4.pdf",
    codeConstant: "PDF_CHAPTER_INSERT_BEFORE_4_PATH",
    mergePdfOnly: true,
    note: "PersonalYearChapterTransitionPage に移行。結合しない（chapterInsertConfig.ts）。",
  },
  {
    id: "ch4",
    label: "第4章扉（レガシー・文字込み全面）",
    runtimePng: "chapter-4-divider.png",
    designPdf: null,
    codeConstant: "PDF_CHAPTER_4_DIVIDER_PATH",
  },
  {
    id: "journal-diary-invite-bg",
    label: "フクロウ先生メッセージ＋あしあと案内（文字なし背景）",
    runtimePng: "journal-diary-invite-bg.png",
    designPdf: null,
    codeConstant: "PDF_JOURNAL_DIARY_INVITE_BG_PATH",
    note: "JournalDiaryInvitePage。shime_honbun / shime_cm1 / shime_cm2 + journal-diary-invite-qr.png。",
  },
  {
    id: "pm-extra",
    label: "フクロウ先生メッセージ＋あしあと案内（レガシー・文字込み全面）",
    runtimePng: "personal-month-intro-extra.png",
    designPdf: null,
    codeConstant: "PDF_PERSONAL_MONTH_INTRO_EXTRA_PATH",
  },
  {
    id: "journal-1",
    label: "あしあと導線 1（レガシー・旧fukuro04）",
    runtimePng: "journal-invite-1.png",
    designPdf: null,
    codeConstant: "PDF_JOURNAL_INVITE_PAGE_1_PATH",
    note: "旧ブリッジ章後メッセージ全面。BridgeAfterMessagePage 移行後は無効（chapterInsertConfig.ts）。",
  },
  {
    id: "journal-2-bg",
    label: "この年大切にしたいこと（文字なし背景）",
    runtimePng: "journal-invite-2-bg.png",
    designPdf: null,
    codeConstant: "PDF_JOURNAL_INVITE_2_BG_PATH",
    note: "JournalPrioritiesPage。Canva: toshi_title / toshi_messe / toshi_thema / toshi_ishiki / toshi_tome。",
  },
  {
    id: "journal-2",
    label: "この年大切にしたいこと（レガシー・文字込み全面）",
    runtimePng: "journal-invite-2.png",
    designPdf: null,
    codeConstant: "PDF_JOURNAL_INVITE_PAGE_2_PATH",
  },
  {
    id: "journal-3-bg",
    label: "この年を振り返って（文字なし背景）",
    runtimePng: "journal-invite-3-bg.png",
    designPdf: null,
    codeConstant: "PDF_JOURNAL_INVITE_3_BG_PATH",
    note: "JournalRetrospectPage。Canva: huri_title / huri_messe / huri01〜huri04。",
  },
  {
    id: "journal-3",
    label: "この年を振り返って（レガシー・文字込み全面）",
    runtimePng: "journal-invite-3.png",
    designPdf: null,
    codeConstant: "PDF_JOURNAL_INVITE_PAGE_3_PATH",
  },
  {
    id: "journal-4-bg",
    label: "余白のページ・左（方眼・文字なし背景）",
    runtimePng: "journal-invite-4-bg.png",
    designPdf: null,
    codeConstant: "PDF_JOURNAL_INVITE_4_BG_PATH",
    note: "JournalMemoLeftPage。生成テキスト: Canva yohaku（余白のページ）のみ。",
  },
  {
    id: "journal-4",
    label: "余白のページ・左（レガシー・文字込み全面）",
    runtimePng: "journal-invite-4.png",
    designPdf: null,
    codeConstant: "PDF_JOURNAL_INVITE_PAGE_4_PATH",
  },
  {
    id: "journal-5-bg",
    label: "余白のページ・右（フクロウつき・文字なし背景）",
    runtimePng: "journal-invite-5-bg.png",
    designPdf: null,
    codeConstant: "PDF_JOURNAL_INVITE_5_BG_PATH",
    note: "JournalMemoRightPage。フクロウ本体は背景 PNG。生成: yohaku / yohaku_fukuro。",
  },
  {
    id: "journal-5",
    label: "余白のページ・右（レガシー・文字込み全面）",
    runtimePng: "journal-invite-5.png",
    designPdf: null,
    codeConstant: "PDF_JOURNAL_INVITE_PAGE_5_PATH",
  },
  {
    id: "afterword-1-bg",
    label: "おわりに・左（背景）",
    runtimePng: "afterword-1-bg.png",
    designPdf: null,
    codeConstant: "PDF_AFTERWORD_1_BG_PATH",
    note: "AfterwordBleedPage 左P。last_title + last_hon1。",
  },
  {
    id: "afterword-2-bg",
    label: "おわりに・右（背景）",
    runtimePng: "afterword-2-bg.png",
    designPdf: null,
    codeConstant: "PDF_AFTERWORD_2_BG_PATH",
    note: "AfterwordBleedPage 右P。last_hon2（フクロウ先生イラスト余白あり）。",
  },
  {
    id: "afterword-1",
    label: "おわりに・左（レガシー・文字込み全面）",
    runtimePng: "afterword-1.png",
    designPdf: null,
    codeConstant: "PDF_AFTERWORD_PAGE_1_PATH",
  },
  {
    id: "afterword-2",
    label: "おわりに・右（レガシー・文字込み全面）",
    runtimePng: "afterword-2.png",
    designPdf: null,
    codeConstant: "PDF_AFTERWORD_PAGE_2_PATH",
  },
  {
    id: "insert-back",
    label: "最終・裏表紙挿入（PDF結合のみ）",
    runtimePng: "",
    designPdf: "final-back-cover-insert.pdf",
    codeConstant: "PDF_FINAL_BACK_COVER_INSERT_PATH",
    mergePdfOnly: true,
    note: "元 ura.pdf。PNG の back-cover.png とは別物。",
  },
  {
    id: "spread-left",
    label: "見開き左（未使用のことが多い）",
    runtimePng: "spread-left.png",
    designPdf: null,
    codeConstant: "PDF_SPREAD_LEFT_PATH",
    note: "showBindingBackground 有効時のみ。現状は低解像度のことが多い。",
  },
  {
    id: "spread-right",
    label: "見開き右（未使用のことが多い）",
    runtimePng: "spread-right.png",
    designPdf: null,
    codeConstant: "PDF_SPREAD_RIGHT_PATH",
  },
  {
    id: "back-cover",
    label: "裏表紙（react-pdf 背景・未使用のことが多い）",
    runtimePng: "back-cover.png",
    designPdf: null,
    codeConstant: "PDF_BACK_COVER_PATH",
    note: "final-back-cover-insert.pdf とは別。",
  },
];

/** assets/ にあって一覧に無い PDF を検出する用 */
export function allDesignPdfNamesForEntry(entry: PdfDesignAssetEntry): string[] {
  const names: string[] = [];
  if (entry.designPdf) names.push(entry.designPdf);
  if (entry.designPdfAliases) names.push(...entry.designPdfAliases);
  return names;
}
